create table if not exists public.portal_runs (
  id bigint generated by default as identity primary key,
  platform text not null,
  status text not null,
  warning text not null default '',
  record_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.bids (
  dedupe_key text primary key,
  platform text not null,
  bid_id text not null default '',
  title text not null,
  agency text not null default '',
  location text not null default '',
  due_date date,
  bid_url text not null default '',
  documents_url text not null default '',
  estimated_value text not null default '',
  description text not null default '',
  scraped_at timestamptz,
  raw_json jsonb not null,
  is_current boolean not null default true,
  last_seen_run_id bigint references public.portal_runs(id),
  updated_at timestamptz not null default now()
);

create index if not exists bids_current_platform_idx
  on public.bids (is_current, platform);

create table if not exists public.company_profiles (
  version integer primary key,
  profile_json jsonb not null,
  created_at timestamptz not null default now()
);

insert into public.company_profiles (version, profile_json)
values (
  1,
  '{"version":1,"service_areas":[],"project_terms":["construction","road","bridge","drainage","concrete","earthwork"],"material_terms":["aggregate","gravel","sand","stone","asphalt","riprap"],"preferred_agencies":[],"excluded_terms":[],"minimum_lead_days":7}'::jsonb
)
on conflict (version) do nothing;

alter table public.portal_runs enable row level security;
alter table public.bids enable row level security;
alter table public.company_profiles enable row level security;

revoke all on public.portal_runs from anon, authenticated;
revoke all on public.bids from anon, authenticated;
revoke all on public.company_profiles from anon, authenticated;
